version: '3.4'
services:
  php:
    image: "${COMPOSE_PHP_IMAGE}"
    env_file:
      - .env
    user: "${UID}:${GID}"
    environment:
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST}"
    volumes:
      - ./app:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/supervisor:/etc/supervisor/conf.d
