version: '3.4'
services:
  php:
    image: "${COMPOSE_PHP_IMAGE}"
    env_file:
      - .env
    user: "${UID}:${GID}"
    environment:
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST}"
    volumes:
      - ./app:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  memcached:
    image: memcached:1.6
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}/tcp"
    volumes:
      - /var/log/mysql
      - /var/lib/mysql
  nginx:
    image: nginx:1.21
    ports:
      - '${NGINX_PORT}:80/tcp'
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
