name: PHP 8.3

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build default
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: default
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=php:8.3-fpm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3
      -
        name: Build composer
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: composer
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-composer
      -
        name: Build composer + supervisor
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: supervisor
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-composer
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-supervisor-composer
      -
        name: Build composer + supervisor + debug
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: debug
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-supervisor-composer
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-debug-supervisor-composer
      -
        name: Build composer + debug
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: debug
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-composer
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-debug-composer
      -
        name: Build supervisor
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: supervisor
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-supervisor
      -
        name: Build supervisor + debug
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: debug
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-supervisor
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-debug-supervisor
      -
        name: Build debug
        uses: docker/build-push-action@v6
        with:
          context: build/php
          target: debug
          pull: true
          push: ${{ github.ref == 'refs/heads/master' }}
          build-args: |
            BASE_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-developer:php-8.3-debug
