name: PHP 8.1

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Default image
        uses: docker/build-push-action@v2
        with:
          context: build/php-7.4-8.1
          target: base
          pull: true
          push: false
          build-args: BASE_IMAGE=php:8.1-fpm
          tags: kovalevpw/php-developer:php-8.1
      -
        name: Build Yii2 image
        uses: docker/build-push-action@v2
        with:
          context: build/php-7.4-8.1
          target: yii2
          pull: true
          push: false
          build-args: BASE_IMAGE=php:8.1-fpm
          tags: kovalevpw/php-developer:php-8.1-yii2
      -
        name: Push Default image
        uses: docker/build-push-action@v2
        with:
          context: build/php-7.4-8.1
          target: base
          pull: false
          push: true
          build-args: BASE_IMAGE=php:8.1-fpm
          tags: kovalevpw/php-developer:php-8.1
        if: success() && github.ref == 'refs/heads/master'
      -
        name: Push Yii2 image
        uses: docker/build-push-action@v2
        with:
          context: build/php-7.4-8.1
          target: yii2
          pull: false
          push: true
          build-args: BASE_IMAGE=php:8.1-fpm
          tags: kovalevpw/php-developer:php-8.1-yii2
        if: success() && github.ref == 'refs/heads/master'
